### ISSUE TITLE
Color palette should discourage shades of red

### ISSUE THREAD

**Issue by fghaas** [aspiers/presentation-template#2]
This theme is somewhat unusual in that it uses green as its predominant highlight color. In the interest of accessibility, considering [up to 10% of the male population is red-green colorblind in some ethnicities](https://en.wikipedia.org/wiki/Color_blindness#Frequency_of_red-green_color_blindness_in_males_of_various_populations), it is probably wise to at least discourage the use of shades of red in the color palette. In particular, giving an example using `bright-magenta` is probably a suboptimal idea, as it will be almost impossible to distinguish from light green for someone who is red-green colorblind.

Switching the example to a blue color is probably better.

**Comment by aspiers** [comment]
On Sun, Apr 10, 2016 at 11:22:11PM -0700, Florian Haas wrote:

> This theme is somewhat unusual in that it uses green as its
> predominant highlight color.
> 
> In the interest of accessibility, considering up to 10% of the male
> population is red-green colorblind in some ethnicities,

That's interesting - I heard it was as high as 1 in 3 males ... but
10% is still significant, of course.

> it is probably wise to at least discourage the use of shades of red
> in the color palette.

True, although really we only have one shade of red in the palette,
unless you count magenta ...

> In particular, giving an example using
> `bright-magenta` is probably a suboptimal idea,

OK, so you do :-)

> as it will be almost
> impossible to distinguish from light green for someone who is
> red-green colorblind.

Right.

> Switching the example to a blue color is probably better.

Which example exactly?

Unfortunately this is not the right place to submit bugs about our
corporate branding color palette, since I have absolutely no influence
over it ...  If you want, I could submit to bugzilla or try to locate
someone in that department?

**Comment by fghaas** [comment]
I'm just observing that your color palette slide mentions `bright-magenta` explicitly:

``` html
    <p>
        Simply use CSS styles in the format:
        <ul>
            <li><code>fg-dark-green</code>
            <li><code>bg-light-purple</code>
        </ul>
        or
        <a href="http://sass-lang.org/guide">Sass</a>
        <a href="http://sass-lang.org/guide#topic-2">variables</a>
        in the format <code>$bright‑magenta</code>.
    </p>
```

... and I'm suggesting that you perhaps give an example using a shade of blue.

**Comment by aspiers** [comment]
Oh, I see!  Yes, I can certainly fix that.
